name: koin_test
description: A testing library for koin.
version: 0.11.0
homepage: https://github.com/pbissonho/koin.dart


environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  koin: ^0.8.0 
  test: ^1.6.0
  kt_dart: ^0.7.0+1
  equatable: ^1.0.0
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.8.0
  mockito: ^4.1.1
  
