name: koin_test
description: A testing library for koin.
version: 0.5.0
homepage: https://github.com/pbissonho/koin.dart
author: Pedro Bissonho <pedro.bissonho@gmail.com>


environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  koin: ^0.2.0
  test: ^1.6.0
  equatable: ^1.0.0
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.8.0
  mockito: ^4.1.1
  
