name: koin_test
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Pedro Bissonho <pedro.bissonho@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  equatable: ^1.0.0
  koin:
    path: /home/pedro/Documents/Github/koin_folder/koin_dart/packages/koin
  mockito: ^4.0.0
  test: ^1.6.0
  meta: ^1.1.6
dev_dependencies:
  pedantic: ^1.8.0
  
