name: koin_test
description: A testing library for koin, makes easy mock of definitions and module testing.
version: 0.12.0
homepage: https://github.com/pbissonho/koin.dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  koin:
    path: ../koin
  kt_dart: ^0.7.0+1
  equatable: ^1.2.2
  test: ^1.6.0
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.8.0
  mockito: ^4.1.1
 
