name: koin_test
description: A testing library for koin, makes easy mock of definitions and module testing.
version: 0.12.1
homepage: https://github.com/pbissonho/koin.dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  koin:
    path: ../koin
  kt_dart: ^0.9.0-nullsafety.0
  test: ^1.16.0-nullsafety.12
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  pedantic: ^1.8.0
  mockito: ^4.1.1
  test_coverage: ^0.5.0
 
