name: koin
description: A pragmatic lightweight dependency injection framework for Dart projects.
version: 0.9.1
homepage: https://github.com/pbissonho/koin.dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  path: ^1.6.0
  equatable: ^1.1.1
  kt_dart: ^0.7.0+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_coverage: ^0.3.0