name: koin
description: A pragmatic lightweight dependency injection framework for Dart projects.
version: 0.13.1+1
homepage: https://github.com/pbissonho/koin.dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  equatable: ^1.2.2
  kt_dart: ^0.7.0+1
  meta: ^1.1.6
  
dev_dependencies:
  effective_dart: ^1.2.0
  test: ^1.6.0
  test_coverage: ^0.3.0