name: koin_bloc
description: A package to make it easier to use Bloc library with Koin.dart.
version: 0.1.0
homepage: https://github.com/pbissonho/koin.dart

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  bloc: ^6.0.1
  koin: ^0.12.1 
dev_dependencies:
  pedantic: ^1.9.0
  koin_test: ^0.11.6
  test: ^1.14.4
