name: koin_bloc
description: A package to make it easier to use Bloc library with Koin.dart.
version: 0.1.2
homepage: https://github.com/pbissonho/koin.dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  bloc: ^7.0.0-nullsafety.3
  koin: 
    path: ../koin
  
dev_dependencies:
  pedantic: ^1.9.0
  koin_test:
    path: ../koin_test
  test: ^1.16.0-nullsafety.12
    