name: koin_bloc
description: A package to make it easier to use Bloc library with Koin.dart.
version: 0.1.1
homepage: https://github.com/pbissonho/koin.dart

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  bloc: ^6.0.1
  koin:
    path: ../koin 
dev_dependencies:
  pedantic: ^1.9.0
  koin_test:
    path: ../koin_test
  test: ^1.14.4
    